[
build
]
  functions = "functions"  # Directory with your serverless functions

[[
redirects
]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[
functions
]
  directory = "functions"