const mongoose = require("mongoose");

const languageSchema = {
  en: {
    type: Boolean,
    default: false,
  },
  ar: {
    type: Boolean,
    default: false,
  },
};

let AmenitiesSchema = mongoose.Schema(
  {
    room: {
      ClothesRack: languageSchema,
      DryingRack: languageSchema,
      Dryer: languageSchema,
      Fan: languageSchema,
      Heating: languageSchema,
      AirConditioning: languageSchema,
      Wardrobe: languageSchema,
      Soundproofing: languageSchema,
      CarpetedFloors: languageSchema,
      Fireplace: languageSchema,
      MosquitoNet: languageSchema,
      SittingArea: languageSchema,
      ElectricBlanket: languageSchema,
      TileFloors: languageSchema,
      ParquetFloors: languageSchema,
      HardwoodFloors: languageSchema,
      IroningBoard: languageSchema,
    },
    bathroom: {
      HotWater: languageSchema,
      Shower: languageSchema,
      Bathtub: languageSchema,
      Hairdryer: languageSchema,
      ToiletPaper: languageSchema,
      Bathrobes: languageSchema,
      Slippers: languageSchema,
      SpaTub: languageSchema,
      Toilet: languageSchema,
      FreeToiletries: languageSchema,
      ToiletSoap: languageSchema,
      PrivateBathroom: languageSchema,
      SharedBathroom: languageSchema,
      Towels: languageSchema,
    },
    mediaAndTechnology: {
      TV: languageSchema,
      CableTV: languageSchema,
      SatelliteTV: languageSchema,
      FlatScreenTV: languageSchema,
      Radio: languageSchema,
      CDPlayer: languageSchema,
      DVDPlayer: languageSchema,
      iPodDockingStation: languageSchema,
      MP3Player: languageSchema,
      Telephone: languageSchema,
      WiFi: languageSchema,
      Computer: languageSchema,
      GameConsole: languageSchema,
      VideoGame: languageSchema,
    },
    foodAndDrink: {
      DiningTable: languageSchema,
      DiningChairs: languageSchema,
      DiningArea: languageSchema,
      Stovetop: languageSchema,
      Oven: languageSchema,
      Toaster: languageSchema,
      Refrigerator: languageSchema,
      Microwave: languageSchema,
      Dishwasher: languageSchema,
      EspressoMachine: languageSchema,
      CoffeeMaker: languageSchema,
      TeaMaker: languageSchema,
      CoffeeMachine: languageSchema,
      Kettle: languageSchema,
      BarbecueGrill: languageSchema,
      OutdoorDiningArea: languageSchema,
      OutdoorSeating: languageSchema,
      OutdoorFireplace: languageSchema,
      OutdoorTable: languageSchema,
      OutdoorChairs: languageSchema,
    },
    servicesAndExtras: {
      ExecutiveLoungeAccess: languageSchema,
      BusinessCenter: languageSchema,
      LaundryService: languageSchema,
      DryCleaningService: languageSchema,
      AlarmClock: languageSchema,
      WakeUpCall: languageSchema,
      TowelDelivery: languageSchema,
      ToiletriesDelivery: languageSchema,
      RoomService: languageSchema,
      BreakfastInRoom: languageSchema,
      IroningService: languageSchema,
    },
    outdoorAndView: {
      Balcony: languageSchema,
      Terrace: languageSchema,
      Patio: languageSchema,
      View: languageSchema,
      GardenView: languageSchema,
      PoolView: languageSchema,
      SeaView: languageSchema,
      MountainView: languageSchema,
      ForestView: languageSchema,
      LakeView: languageSchema,
      RiverView: languageSchema,
      BeachView: languageSchema,
      CityView: languageSchema,
      ParkView: languageSchema,
      LandmarkView: languageSchema,
      QuietStreetView: languageSchema,
    },
    accessibility: {
      RoomIsLocatedOnTheGroundFloor: languageSchema,
      RoomIsCompletelyWheelchairAccessible: languageSchema,
      RoomIsAccessibleByElevator: languageSchema,
      RoomIsAccessibleByStairs: languageSchema,
      ToiletIsWheelchairAccessible: languageSchema,
    },
    entertainmentAndFamilyServices: {
      BabySafetyGate: languageSchema,
      BoardGames: languageSchema,
      ChildrensClub: languageSchema,
      ChildrensMenu: languageSchema,
      ChildrensPlayArea: languageSchema,
      ChildrensPlayground: languageSchema,
      BooksForChildren: languageSchema,
      BabySittingService: languageSchema,
      ChildSafetySocketCover: languageSchema,
      ChildSafetyLock: languageSchema,
    },
  },
  { timestamps: true },
  { collection: "amenities" }
);

let Amenities = mongoose.model("amenities", AmenitiesSchema);

module.exports = Amenities;
